### ISSUE TITLE
Task 'probe hosts' in run_gdeploy.yml task file needs to have the abillity to refer to any list of hosts or IPs

### ISSUE THREAD

**Issue by ascerra** [oasis-roles/gluster_gdeploy#2]
As it stands right now I believe that this task will run the gluster peer probe command on the public facing IPs of the machines that are a part of 'ansible_play_hosts'. For the Upshift project we are required to probe the hosts with a private 10g connection. In order for us to point to these IPs we will need this task to be capable of accepting a variable that we pass it.

**Comment by greg-hellings** [comment]
Fixed.
