### ISSUE TITLE
Allow for version specifications

### ISSUE THREAD

**Issue by ascerra** [oasis-roles/gluster_gdeploy#8]
The rpm that holds redhat-storage-server contains multiple different product versions. Because of this we need a way inside the role when installing this package to specify which version of the package we are installing. This is needed for regression testing. Specifying a different version will consists of appending the version to the end of the package name for example.
'redhat-storage-server-3.3.0.2-1.el7rhgs'
The '-' in between redhat-strorage-server' and '3.3.0.2-1.el7rhgs' is needed

**Comment by seandst** [comment]
@greg-hellings Any reason not to move everything in `vars/main.yml` over into defaults for better override ability?

**Comment by greg-hellings** [comment]
Yes. If we do that we allow a user to install arbitrary applications ("Why is Firefox in your list of RPMs for Gluster?!"). We also make it a royal PITA to maintain if we need to change the list.

I'm already working this issue in a way similar to how we install different versions of Jenkins in Cinch.

**Comment by seandst** [comment]
Good to know. We've got a few package lists in defaults in other roles, so this will probably (and rightly so) result in some minor style guide changes as well as some role changes.

**Comment by greg-hellings** [comment]
@ascerra You can check against #10 to see if it works for you

**Comment by ascerra** [comment]
I've tested this change and it works for me! Thank you

**Comment by greg-hellings** [comment]
Merged to master
